//! Dedicated LUKS key-wrapping payloads.
//!
//! A disk key is 32 random bytes generated by the setup tool. The phone wraps
//! those bytes with a biometric-gated AES key whose alias is reserved for
//! LUKS. ECDSA signatures never become key material.

use crate::cbor::{Reader, Writer};
use crate::{bytes_equal, check_text, ProtocolError, Result, MAX_APPLICATION_PAYLOAD_BYTES};

pub const OPERATION_ENROLL: &str = "luks.enroll";
pub const OPERATION_UNLOCK: &str = "luks.unlock";
pub const LUKS_SCHEMA: u64 = 1;
pub const DISK_KEY_LEN: usize = 32;
pub const VOLUME_BINDING_LEN: usize = 32;
pub const MAX_WRAPPER_BYTES: usize = 512;

const ENROLL_REQUEST_FIELDS: u64 = 5;
const ENROLL_RESPONSE_FIELDS: u64 = 3;
const UNLOCK_REQUEST_FIELDS: u64 = 6;
const UNLOCK_RESPONSE_FIELDS: u64 = 2;
const WRAPPED_KEY_FIELDS: u64 = 4;
const MAX_NAME_UNITS: usize = 255;
const MAX_ID_UNITS: usize = 64;

fn wipe(buffer: &mut [u8]) {
    for byte in buffer.iter_mut() {
        unsafe { core::ptr::write_volatile(byte, 0) };
    }
    core::sync::atomic::compiler_fence(core::sync::atomic::Ordering::SeqCst);
}

#[derive(Clone, PartialEq, Eq)]
pub struct EnrollRequest {
    pub verifier_name: String,
    pub volume_name: String,
    pub volume_binding: [u8; VOLUME_BINDING_LEN],
    pub disk_key: Vec<u8>,
}

impl Drop for EnrollRequest {
    fn drop(&mut self) {
        wipe(&mut self.disk_key);
    }
}

impl EnrollRequest {
    pub fn validate(&self) -> Result<()> {
        names(&self.verifier_name, &self.volume_name)?;
        key(&self.disk_key)
    }

    pub fn encode(&self) -> Vec<u8> {
        let mut writer = Writer::new();
        writer.array(ENROLL_REQUEST_FIELDS);
        writer.uint(LUKS_SCHEMA);
        writer.text(&self.verifier_name);
        writer.text(&self.volume_name);
        writer.bytes(&self.volume_binding);
        writer.bytes(&self.disk_key);
        writer.into_bytes()
    }

    pub fn decode(payload: &[u8]) -> Result<Self> {
        let mut reader = open(payload, ENROLL_REQUEST_FIELDS)?;
        let value = Self {
            verifier_name: reader.text()?.to_owned(),
            volume_name: reader.text()?.to_owned(),
            volume_binding: fixed("volumeBinding", reader.bytes()?)?,
            disk_key: reader.bytes()?.to_vec(),
        };
        finish(reader, &value.encode(), payload)?;
        value.validate()?;
        Ok(value)
    }
}

#[derive(Clone, PartialEq, Eq)]
pub struct EnrollResponse {
    pub credential_id: String,
    pub wrapper: Vec<u8>,
}

impl EnrollResponse {
    pub fn validate(&self) -> Result<()> {
        check_text("credentialId", &self.credential_id, MAX_ID_UNITS)?;
        wrapper(&self.wrapper)
    }

    pub fn encode(&self) -> Vec<u8> {
        let mut writer = Writer::new();
        writer.array(ENROLL_RESPONSE_FIELDS);
        writer.uint(LUKS_SCHEMA);
        writer.text(&self.credential_id);
        writer.bytes(&self.wrapper);
        writer.into_bytes()
    }

    pub fn decode(payload: &[u8]) -> Result<Self> {
        let mut reader = open(payload, ENROLL_RESPONSE_FIELDS)?;
        let value = Self {
            credential_id: reader.text()?.to_owned(),
            wrapper: reader.bytes()?.to_vec(),
        };
        finish(reader, &value.encode(), payload)?;
        value.validate()?;
        Ok(value)
    }
}

#[derive(Clone, PartialEq, Eq)]
pub struct UnlockRequest {
    pub verifier_name: String,
    pub volume_name: String,
    pub volume_binding: [u8; VOLUME_BINDING_LEN],
    pub credential_id: String,
    pub wrapper: Vec<u8>,
}

impl UnlockRequest {
    pub fn validate(&self) -> Result<()> {
        names(&self.verifier_name, &self.volume_name)?;
        check_text("credentialId", &self.credential_id, MAX_ID_UNITS)?;
        wrapper(&self.wrapper)
    }

    pub fn encode(&self) -> Vec<u8> {
        let mut writer = Writer::new();
        writer.array(UNLOCK_REQUEST_FIELDS);
        writer.uint(LUKS_SCHEMA);
        writer.text(&self.verifier_name);
        writer.text(&self.volume_name);
        writer.bytes(&self.volume_binding);
        writer.text(&self.credential_id);
        writer.bytes(&self.wrapper);
        writer.into_bytes()
    }

    pub fn decode(payload: &[u8]) -> Result<Self> {
        let mut reader = open(payload, UNLOCK_REQUEST_FIELDS)?;
        let value = Self {
            verifier_name: reader.text()?.to_owned(),
            volume_name: reader.text()?.to_owned(),
            volume_binding: fixed("volumeBinding", reader.bytes()?)?,
            credential_id: reader.text()?.to_owned(),
            wrapper: reader.bytes()?.to_vec(),
        };
        finish(reader, &value.encode(), payload)?;
        value.validate()?;
        Ok(value)
    }
}

#[derive(Clone, PartialEq, Eq)]
pub struct UnlockResponse {
    pub disk_key: Vec<u8>,
}

impl Drop for UnlockResponse {
    fn drop(&mut self) {
        wipe(&mut self.disk_key);
    }
}

impl UnlockResponse {
    pub fn validate(&self) -> Result<()> {
        key(&self.disk_key)
    }

    pub fn encode(&self) -> Vec<u8> {
        let mut writer = Writer::new();
        writer.array(UNLOCK_RESPONSE_FIELDS);
        writer.uint(LUKS_SCHEMA);
        writer.bytes(&self.disk_key);
        writer.into_bytes()
    }

    pub fn decode(payload: &[u8]) -> Result<Self> {
        let mut reader = open(payload, UNLOCK_RESPONSE_FIELDS)?;
        let value = Self {
            disk_key: reader.bytes()?.to_vec(),
        };
        finish(reader, &value.encode(), payload)?;
        value.validate()?;
        Ok(value)
    }
}

/// Public data persisted in the initrd configuration.
#[derive(Clone, PartialEq, Eq)]
pub struct WrappedVolumeKey {
    pub volume_binding: [u8; VOLUME_BINDING_LEN],
    pub credential_id: String,
    pub wrapper: Vec<u8>,
}

impl WrappedVolumeKey {
    pub fn validate(&self) -> Result<()> {
        check_text("credentialId", &self.credential_id, MAX_ID_UNITS)?;
        wrapper(&self.wrapper)
    }

    pub fn encode(&self) -> Vec<u8> {
        let mut writer = Writer::new();
        writer.array(WRAPPED_KEY_FIELDS);
        writer.uint(LUKS_SCHEMA);
        writer.bytes(&self.volume_binding);
        writer.text(&self.credential_id);
        writer.bytes(&self.wrapper);
        writer.into_bytes()
    }

    pub fn decode(payload: &[u8]) -> Result<Self> {
        let mut reader = open(payload, WRAPPED_KEY_FIELDS)?;
        let value = Self {
            volume_binding: fixed("volumeBinding", reader.bytes()?)?,
            credential_id: reader.text()?.to_owned(),
            wrapper: reader.bytes()?.to_vec(),
        };
        finish(reader, &value.encode(), payload)?;
        value.validate()?;
        Ok(value)
    }
}

fn names(verifier: &str, volume: &str) -> Result<()> {
    check_text("verifierName", verifier, MAX_NAME_UNITS)?;
    check_text("volumeName", volume, MAX_NAME_UNITS)
}

fn key(value: &[u8]) -> Result<()> {
    if value.len() != DISK_KEY_LEN {
        return Err(ProtocolError::FieldLength {
            field: "diskKey",
            expected: DISK_KEY_LEN,
            actual: value.len(),
        });
    }
    Ok(())
}

fn wrapper(value: &[u8]) -> Result<()> {
    if value.is_empty() || value.len() > MAX_WRAPPER_BYTES {
        return Err(ProtocolError::PayloadSize(value.len()));
    }
    Ok(())
}

fn open(payload: &[u8], fields: u64) -> Result<Reader<'_>> {
    if payload.is_empty() || payload.len() > MAX_APPLICATION_PAYLOAD_BYTES {
        return Err(ProtocolError::PayloadSize(payload.len()));
    }
    let mut reader = Reader::new(payload);
    let actual = reader.array()?;
    if actual != fields {
        return Err(ProtocolError::FrameShape {
            expected: fields,
            actual,
        });
    }
    let schema = reader.uint()?;
    if schema != LUKS_SCHEMA {
        return Err(ProtocolError::UnsupportedVersion(schema));
    }
    Ok(reader)
}

fn finish(reader: Reader<'_>, encoded: &[u8], input: &[u8]) -> Result<()> {
    reader.finish()?;
    if !bytes_equal(encoded, input) {
        return Err(ProtocolError::NotCanonical);
    }
    Ok(())
}

fn fixed<const N: usize>(field: &'static str, value: &[u8]) -> Result<[u8; N]> {
    value.try_into().map_err(|_| ProtocolError::FieldLength {
        field,
        expected: N,
        actual: value.len(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::encoding::to_hex;

    fn unlock() -> UnlockRequest {
        UnlockRequest {
            verifier_name: "Workstation".into(),
            volume_name: "cryptroot".into(),
            volume_binding: core::array::from_fn(|index| index as u8),
            credential_id: "desktop-diskUnlock-v1".into(),
            wrapper: vec![9; 60],
        }
    }

    #[test]
    fn unlock_request_has_a_cross_language_vector() {
        assert_eq!(
            to_hex(&unlock().encode()),
            concat!(
                "86016b576f726b73746174696f6e696372797074726f6f745820000102030405",
                "060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f756465736b",
                "746f702d6469736b556e6c6f636b2d7631583c090909090909090909090909",
                "0909090909090909090909090909090909090909090909090909090909090909",
                "09090909090909090909090909090909"
            )
        );
    }

    #[test]
    fn payloads_and_persistent_wrapper_round_trip() {
        let enroll = EnrollRequest {
            verifier_name: "Workstation".into(),
            volume_name: "cryptroot".into(),
            volume_binding: [3; 32],
            disk_key: vec![4; 32],
        };
        assert!(EnrollRequest::decode(&enroll.encode()).unwrap() == enroll);
        let response = EnrollResponse {
            credential_id: "disk-v1".into(),
            wrapper: vec![5; 60],
        };
        assert!(EnrollResponse::decode(&response.encode()).unwrap() == response);
        assert!(UnlockRequest::decode(&unlock().encode()).unwrap() == unlock());
        let answer = UnlockResponse {
            disk_key: vec![6; 32],
        };
        assert!(UnlockResponse::decode(&answer.encode()).unwrap() == answer);
        let stored = WrappedVolumeKey {
            volume_binding: [7; 32],
            credential_id: "disk-v1".into(),
            wrapper: vec![8; 60],
        };
        assert!(WrappedVolumeKey::decode(&stored.encode()).unwrap() == stored);
    }

    #[test]
    fn wrong_sizes_versions_and_shapes_fail_closed() {
        let mut bad = UnlockResponse {
            disk_key: vec![0; 31],
        };
        assert!(bad.validate().is_err());
        bad.disk_key.push(0);
        let mut encoded = bad.encode();
        encoded[1] = 2;
        assert!(UnlockResponse::decode(&encoded).is_err());
        assert!(UnlockRequest::decode(&bad.encode()).is_err());
        let mut trailing = unlock().encode();
        trailing.push(0);
        assert!(UnlockRequest::decode(&trailing).is_err());
    }

    #[test]
    fn application_envelope_accepts_only_the_luks_namespace() {
        for operation in [OPERATION_ENROLL, OPERATION_UNLOCK] {
            let frame = crate::ApplicationFrame {
                protocol_version: crate::PROTOCOL_VERSION,
                kind: crate::ApplicationFrameKind::Request,
                request_id: "request-1".into(),
                session_binding: [0; 32],
                operation: operation.into(),
                issued_at_ms: 1,
                expires_at_ms: 2,
                payload: unlock().encode(),
            };
            frame.validate().unwrap();
        }
    }
}
